name: Tests

# * Controls
# Controls when the action will run.
on:
  push:
    paths:
      - '.github/workflows/*'
      - '.github/*'
      - 'src/Dockerfile'
      - 'src/rootfs/*'
      - 'src/hook/*'
      - 'src/builds/*'
      - 'src/*.sh'
      - 'src/VERSIONS'
      - 'tests/**'
    branches-ignore:
      - 'master'
      - 'main'
  pull_request:
    paths:
      - '.github/workflows/*'
      - '.github/*'
      - 'src/Dockerfile'
      - 'src/rootfs/*'
      - 'src/hook/*'
      - 'src/builds/*'
      - 'src/*.sh'
      - 'tests/**'
    branches-ignore:
      - 'master'
      - 'main'
  workflow_dispatch:

# * Jobs
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v2

      - name: Check shell files (shellcheck)
        run: |
          sudo apt-get update -y
          sudo apt-get install shellcheck
          cd ${GITHUB_WORKSPACE}/tests
          .bats-battery/bats-core/bin/bats 01.shellchecks.bats

      - name: Check Dockerfile (hadolint)
        run: |
          cd ${GITHUB_WORKSPACE}/tests
          .bats-battery/bats-core/bin/bats 02.dockerfile_check.bats

      - name: alt-s6-builder. Build. Check image and container. Check builds.
        run: |
          echo "::group::Build image"
          echo "Build image"
          set -a; source ${GITHUB_WORKSPACE}/src/VERSIONS ; set +a;
          export IMAGE="${IMAGE:-${IMAGE_REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG}}"
          cd ${GITHUB_WORKSPACE}/src/hook
          ./build.sh
          echo "::endgroup::"

          echo "::group::Check image and container"
          cd ${GITHUB_WORKSPACE}/tests
          echo "Check docker image (dockle)"
          .bats-battery/bats-core/bin/bats 03.docker_image_check.bats
          echo "Check docker container"
          .bats-battery/bats-core/bin/bats 04.container_check.bats
          echo "Check builds"
          .bats-battery/bats-core/bin/bats 05.builds_check.bats
          echo "::endgroup::"
